### PR TITLE
Run docker-containers as user instead of root.

### PR DESCRIPTION
**Pull request by OzanAlpay**
Running docker containers as user instead of root feature implemented.

### CODE REVIEW

**Comment by bulwahn** [comment]
@OzanAlpay Did you see that Codacy is pointing out that this is not good. Can you check if it possible to write the bash expression in such a way that it works and Codacy does not complain? You need probably need to go through the bash documentation to find out which possibilities there are for quoting.

**Comment by OzanAlpay** [comment]
I will look and fix this problem soon

**Comment by OzanAlpay** [comment]
I have looked that warning again, and interestingly find-out  (as codacy complained) even without any ```'``` it works well.

I analyzed outputs after called script with different kernel-configurations and saw that it is working. Such as after calling with allyesconfig, I saw output:
```
scripts/kconfig/conf  --allyesconfig Kconfig
```

So I updated my request according to that without using any ```'```. I will also update my other pull request( #18 ), that Codacy complained about.
By the way my home setup is:
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Docker version 18.03.1-ce, build 9ee9f40

**Comment by bulwahn** [comment]
This change was included into master. So, we close this pull request successfully.

**Pull request closed without merging**
